version: '3.8'

services:
  url_shortner_service:
    build:
      context: ./url_shortner_service
    ports:
      - "9005:9005"
    env_file:
      - ./url_shortner_service/.env
    volumes:
      - ./url_shortner_service:/app
    command: sh runserver.sh
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data

  web:
    build:
      context: ./web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - url_shortner_service
      - web
