# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY . .

# Make port 9005 available to the world outside this container
EXPOSE 9005

# Run runserver.sh when the container launches
CMD ["uvicorn", "main:app", "--reload", "--port", "9005"]
